services:
  mongodb:
    image: mongo:latest
    container_name: guidebook-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=guidebook
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
