apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guidebook

resources:
  - namespace.yaml
  - deployment.yaml
  - deployment-mongodb.yaml
  - service-frontend.yaml
  - service-backend.yaml
  - service-mongodb.yaml
  - ingress.yaml

commonLabels:
  app: guidebook
