apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: guidebook
    component: mongodb
spec:
  type: ClusterIP
  selector:
    app: guidebook
    component: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
