apiVersion: v1
kind: Service
metadata:
  name: guidebook-frontend
  labels:
    app: guidebook
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: guidebook
    component: app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
